name: Publish Docker image

on:
  schedule:
    - cron: '38 5 * * *'
  push:
    branches: [ master ]

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get latest upstream release
        id: nlef
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: nlef/moonraker-telegram-bot

      - name: Check if image for release exists
        id: check-release
        uses: hipcamp/docker-tag-exists@v1
        with:
          image: alefchak/moonraker-telegram-bot
          tag: ${{ steps.nlef.outputs.release }}

      - name: Check out the repo
        uses: actions/checkout@v2
        if: steps.check-release.outputs.tag-exists != 'true'
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: steps.check-release.outputs.tag-exists != 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        if: steps.check-release.outputs.tag-exists != 'true'
        with:
          images: alefchak/moonraker-telegram-bot
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            ${{ steps.nlef.outputs.release }}

      - name: Build and push Docker image
        if: steps.check-release.outputs.tag-exists != 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
